###
POST http://localhost:5050/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpw"
}

###
POST http://localhost:5050/auth/sign-up
Content-Type: application/json

{
  "username": "admin",
  "displayName": "admin",
  "password": "adminpw"
}

###
GET http://localhost:5050/habits

###
GET http://localhost:5050/journal

###
GET http://localhost:5050/tasks